version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install
      - npx playwright install chromium
      - npx playwright install-deps chromium
  build:
    commands:
      - npm run test:ui:headless
