version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install
      - npx playwright install --with-deps chromium
  build:
    commands:
      - npm run test
  post_build:
      commands:
        - echo Build completed on `date`

artifacts:
  files:
    - 'playwright-report/index.html'
  name: playwright_moviedb_artifacts-$(date +%Y-%m-%d)