version: 0.2

env:
  secrets-manager:
    SECRET_VALUE: "arn:aws:secretsmanager:eu-north-1:115049195310:secret:aws-secrets-moviedb-gUgN5c"
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install
      - npx playwright install --with-deps chromium
  build:
    commands:
      - echo $SECRET_VALUE
      - npm run test:ui:headless
  post_build:
      commands:
        - echo Build completed on `date`

artifacts:
  type: CodePipeline
  name: MovieDBArtifact
  packaging: NONE
