version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install
      - npx playwright install --with-deps chromium
  build:
    commands:
      - echo Build started on `date`
      - echo Building and running tests
      - npm test
  post_build:
      commands:
        - if [ $? -ne 0 ]; then
          echo "Tests failed. Failing the build."
          exit 1
        else
          echo "Tests passed. Build successful."
        fi

reports:
  test-report:
    files:
      - "**/results.xml"
    file-format: "JUNITXML" 
